/* Generated By:JJTree: Do not edit this line. .\SyntaxTreeBuilderTreeConstants.java */

package org.openrdf.query.parser.sparql.ast;

public interface SyntaxTreeBuilderTreeConstants
{
  public int JJTQUERYCONTAINER = 0;
  public int JJTVOID = 1;
  public int JJTBASEDECL = 2;
  public int JJTPREFIXDECL = 3;
  public int JJTSELECTQUERY = 4;
  public int JJTSELECT = 5;
  public int JJTCONSTRUCTQUERY = 6;
  public int JJTCONSTRUCT = 7;
  public int JJTDESCRIBEQUERY = 8;
  public int JJTDESCRIBE = 9;
  public int JJTASKQUERY = 10;
  public int JJTDATASETCLAUSE = 11;
  public int JJTWHERECLAUSE = 12;
  public int JJTORDERCLAUSE = 13;
  public int JJTORDERCONDITION = 14;
  public int JJTLIMIT = 15;
  public int JJTOFFSET = 16;
  public int JJTGRAPHPATTERNGROUP = 17;
  public int JJTBASICGRAPHPATTERN = 18;
  public int JJTOPTIONALGRAPHPATTERN = 19;
  public int JJTGRAPHGRAPHPATTERN = 20;
  public int JJTUNIONGRAPHPATTERN = 21;
  public int JJTCONSTRAINT = 22;
  public int JJTFUNCTIONCALL = 23;
  public int JJTTRIPLESSAMESUBJECT = 24;
  public int JJTPROPERTYLIST = 25;
  public int JJTOBJECTLIST = 26;
  public int JJTIRI = 27;
  public int JJTBLANKNODEPROPERTYLIST = 28;
  public int JJTCOLLECTION = 29;
  public int JJTVAR = 30;
  public int JJTOR = 31;
  public int JJTAND = 32;
  public int JJTCOMPARE = 33;
  public int JJTMATH = 34;
  public int JJTNOT = 35;
  public int JJTNUMERICLITERAL = 36;
  public int JJTSTR = 37;
  public int JJTLANG = 38;
  public int JJTLANGMATCHES = 39;
  public int JJTDATATYPE = 40;
  public int JJTBOUND = 41;
  public int JJTSAMETERM = 42;
  public int JJTISIRI = 43;
  public int JJTISBLANK = 44;
  public int JJTISLITERAL = 45;
  public int JJTREGEXEXPRESSION = 46;
  public int JJTRDFLITERAL = 47;
  public int JJTTRUE = 48;
  public int JJTFALSE = 49;
  public int JJTSTRING = 50;
  public int JJTQNAME = 51;
  public int JJTBLANKNODE = 52;


  public String[] jjtNodeName = {
    "QueryContainer",
    "void",
    "BaseDecl",
    "PrefixDecl",
    "SelectQuery",
    "Select",
    "ConstructQuery",
    "Construct",
    "DescribeQuery",
    "Describe",
    "AskQuery",
    "DatasetClause",
    "WhereClause",
    "OrderClause",
    "OrderCondition",
    "Limit",
    "Offset",
    "GraphPatternGroup",
    "BasicGraphPattern",
    "OptionalGraphPattern",
    "GraphGraphPattern",
    "UnionGraphPattern",
    "Constraint",
    "FunctionCall",
    "TriplesSameSubject",
    "PropertyList",
    "ObjectList",
    "IRI",
    "BlankNodePropertyList",
    "Collection",
    "Var",
    "Or",
    "And",
    "Compare",
    "Math",
    "Not",
    "NumericLiteral",
    "Str",
    "Lang",
    "LangMatches",
    "Datatype",
    "Bound",
    "SameTerm",
    "IsIRI",
    "IsBlank",
    "IsLiteral",
    "RegexExpression",
    "RDFLiteral",
    "True",
    "False",
    "String",
    "QName",
    "BlankNode",
  };
}
