# SERVICE join with subselect for SES-1017

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX test: <http://example.org/> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 

SELECT ?page ?redirectPage
WHERE {
 SERVICE <http://dbpedia.org/sparql>
     {
        ?res foaf:page ?page .
        OPTIONAL {
             ?res <http://dbpedia.org/ontology/wikiPageRedirects> ?rd.
             ?rd foaf:page ?redirectPage .
        }
     }
 { SELECT ?res
   WHERE {
     test:Obama owl:sameAs ?res . 
     FILTER(REGEX(str(?res), "^http://dbpedia.org/resource/")) 
   }
   LIMIT 1
 }
 } 