/* Generated By:JJTree&JavaCC: Do not edit this line. SyntaxTreeBuilderConstants.java */
package org.openrdf.query.parser.serql.ast;

public interface SyntaxTreeBuilderConstants {

	int EOF = 0;

	int SINGLE_LINE_COMMENT = 5;

	int EQ = 6;

	int NE = 7;

	int LT = 8;

	int LE = 9;

	int GE = 10;

	int GT = 11;

	int STAR = 12;

	int COMMA = 13;

	int SEMICOLON = 14;

	int LBRACE = 15;

	int RBRACE = 16;

	int LPAREN = 17;

	int RPAREN = 18;

	int LBRACK = 19;

	int RBRACK = 20;

	int USING = 21;

	int NAMESPACE = 22;

	int SELECT = 23;

	int CONSTRUCT = 24;

	int DISTINCT = 25;

	int FROM = 26;

	int CONTEXT = 27;

	int WHERE = 28;

	int LIMIT = 29;

	int OFFSET = 30;

	int TRUE = 31;

	int FALSE = 32;

	int NOT = 33;

	int AND = 34;

	int OR = 35;

	int LIKE = 36;

	int IGNORE = 37;

	int CASE = 38;

	int LABEL = 39;

	int LANG = 40;

	int DATATYPE = 41;

	int LOCALNAME = 42;

	int BOUND = 43;

	int NULL = 44;

	int ISRESOURCE = 45;

	int ISBNODE = 46;

	int ISURI = 47;

	int ISLITERAL = 48;

	int AS = 49;

	int UNION = 50;

	int MINUS = 51;

	int INTERSECT = 52;

	int ANY = 53;

	int ALL = 54;

	int IN = 55;

	int EXISTS = 56;

	int LANG_LITERAL = 57;

	int DATATYPED_LITERAL = 58;

	int STRING = 59;

	int SAFE_CHAR = 60;

	int ESCAPED_CHAR = 61;

	int UNICODE_ESC = 62;

	int LANG_TAG = 63;

	int URI = 64;

	int SCHEME = 65;

	int QNAME = 66;

	int BNODE = 67;

	int PREFIX_NAME = 68;

	int POS_INTEGER = 69;

	int NEG_INTEGER = 70;

	int DECIMAL = 71;

	int HEX = 72;

	int ALPHA = 73;

	int NUM = 74;

	int NCNAME = 75;

	int NCNAME_CHAR = 76;

	int LETTER = 77;

	int BASECHAR = 78;

	int IDEOGRAPHIC = 79;

	int COMBINING_CHAR = 80;

	int DIGIT = 81;

	int EXTENDER = 82;

	int DEFAULT = 0;

	String[] tokenImage = {
			"<EOF>",
			"\" \"",
			"\"\\t\"",
			"\"\\n\"",
			"\"\\r\"",
			"<SINGLE_LINE_COMMENT>",
			"\"=\"",
			"\"!=\"",
			"\"<\"",
			"\"<=\"",
			"\">=\"",
			"\">\"",
			"\"*\"",
			"\",\"",
			"\";\"",
			"\"{\"",
			"\"}\"",
			"\"(\"",
			"\")\"",
			"\"[\"",
			"\"]\"",
			"\"using\"",
			"\"namespace\"",
			"\"select\"",
			"\"construct\"",
			"\"distinct\"",
			"\"from\"",
			"\"context\"",
			"\"where\"",
			"\"limit\"",
			"\"offset\"",
			"\"true\"",
			"\"false\"",
			"\"not\"",
			"\"and\"",
			"\"or\"",
			"\"like\"",
			"\"ignore\"",
			"\"case\"",
			"\"label\"",
			"\"lang\"",
			"\"datatype\"",
			"\"localname\"",
			"\"bound\"",
			"\"null\"",
			"\"isResource\"",
			"\"isBNode\"",
			"\"isURI\"",
			"\"isLiteral\"",
			"\"as\"",
			"\"union\"",
			"\"minus\"",
			"\"intersect\"",
			"\"any\"",
			"\"all\"",
			"\"in\"",
			"\"exists\"",
			"<LANG_LITERAL>",
			"<DATATYPED_LITERAL>",
			"<STRING>",
			"<SAFE_CHAR>",
			"<ESCAPED_CHAR>",
			"<UNICODE_ESC>",
			"<LANG_TAG>",
			"<URI>",
			"<SCHEME>",
			"<QNAME>",
			"<BNODE>",
			"<PREFIX_NAME>",
			"<POS_INTEGER>",
			"<NEG_INTEGER>",
			"<DECIMAL>",
			"<HEX>",
			"<ALPHA>",
			"<NUM>",
			"<NCNAME>",
			"<NCNAME_CHAR>",
			"<LETTER>",
			"<BASECHAR>",
			"<IDEOGRAPHIC>",
			"<COMBINING_CHAR>",
			"<DIGIT>",
			"<EXTENDER>", };

}
