/*******************************************************************************
 * Copyright (c) 2015, Eclipse Foundation, Inc. and its licensors.
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * - Neither the name of the Eclipse Foundation, Inc. nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission. 
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. SyntaxTreeBuilderVisitor.java Version 5.0 */
package org.openrdf.query.parser.serql.ast;

public interface SyntaxTreeBuilderVisitor
{
  public Object visit(SimpleNode node, Object data) throws VisitorException;
  public Object visit(ASTQueryContainer node, Object data) throws VisitorException;
  public Object visit(ASTNamespaceDecl node, Object data) throws VisitorException;
  public Object visit(ASTTupleUnion node, Object data) throws VisitorException;
  public Object visit(ASTTupleMinus node, Object data) throws VisitorException;
  public Object visit(ASTTupleIntersect node, Object data) throws VisitorException;
  public Object visit(ASTGraphUnion node, Object data) throws VisitorException;
  public Object visit(ASTGraphMinus node, Object data) throws VisitorException;
  public Object visit(ASTGraphIntersect node, Object data) throws VisitorException;
  public Object visit(ASTSelectQuery node, Object data) throws VisitorException;
  public Object visit(ASTSelect node, Object data) throws VisitorException;
  public Object visit(ASTProjectionElem node, Object data) throws VisitorException;
  public Object visit(ASTConstructQuery node, Object data) throws VisitorException;
  public Object visit(ASTConstruct node, Object data) throws VisitorException;
  public Object visit(ASTQueryBody node, Object data) throws VisitorException;
  public Object visit(ASTFrom node, Object data) throws VisitorException;
  public Object visit(ASTWhere node, Object data) throws VisitorException;
  public Object visit(ASTOrderBy node, Object data) throws VisitorException;
  public Object visit(ASTLimit node, Object data) throws VisitorException;
  public Object visit(ASTOffset node, Object data) throws VisitorException;
  public Object visit(ASTPathExprList node, Object data) throws VisitorException;
  public Object visit(ASTPathExprUnion node, Object data) throws VisitorException;
  public Object visit(ASTBasicPathExpr node, Object data) throws VisitorException;
  public Object visit(ASTOptPathExpr node, Object data) throws VisitorException;
  public Object visit(ASTBasicPathExprTail node, Object data) throws VisitorException;
  public Object visit(ASTOptPathExprTail node, Object data) throws VisitorException;
  public Object visit(ASTEdge node, Object data) throws VisitorException;
  public Object visit(ASTNode node, Object data) throws VisitorException;
  public Object visit(ASTNodeElem node, Object data) throws VisitorException;
  public Object visit(ASTReifiedStat node, Object data) throws VisitorException;
  public Object visit(ASTOrderExpr node, Object data) throws VisitorException;
  public Object visit(ASTOr node, Object data) throws VisitorException;
  public Object visit(ASTAnd node, Object data) throws VisitorException;
  public Object visit(ASTBooleanConstant node, Object data) throws VisitorException;
  public Object visit(ASTNot node, Object data) throws VisitorException;
  public Object visit(ASTBound node, Object data) throws VisitorException;
  public Object visit(ASTSameTerm node, Object data) throws VisitorException;
  public Object visit(ASTIsResource node, Object data) throws VisitorException;
  public Object visit(ASTIsLiteral node, Object data) throws VisitorException;
  public Object visit(ASTIsURI node, Object data) throws VisitorException;
  public Object visit(ASTIsBNode node, Object data) throws VisitorException;
  public Object visit(ASTLangMatches node, Object data) throws VisitorException;
  public Object visit(ASTRegex node, Object data) throws VisitorException;
  public Object visit(ASTExists node, Object data) throws VisitorException;
  public Object visit(ASTCompare node, Object data) throws VisitorException;
  public Object visit(ASTCompareAny node, Object data) throws VisitorException;
  public Object visit(ASTCompareAll node, Object data) throws VisitorException;
  public Object visit(ASTLike node, Object data) throws VisitorException;
  public Object visit(ASTIn node, Object data) throws VisitorException;
  public Object visit(ASTInList node, Object data) throws VisitorException;
  public Object visit(ASTCompOperator node, Object data) throws VisitorException;
  public Object visit(ASTVar node, Object data) throws VisitorException;
  public Object visit(ASTDatatype node, Object data) throws VisitorException;
  public Object visit(ASTLang node, Object data) throws VisitorException;
  public Object visit(ASTLabel node, Object data) throws VisitorException;
  public Object visit(ASTNamespace node, Object data) throws VisitorException;
  public Object visit(ASTLocalName node, Object data) throws VisitorException;
  public Object visit(ASTStr node, Object data) throws VisitorException;
  public Object visit(ASTFunctionCall node, Object data) throws VisitorException;
  public Object visit(ASTArgList node, Object data) throws VisitorException;
  public Object visit(ASTURI node, Object data) throws VisitorException;
  public Object visit(ASTQName node, Object data) throws VisitorException;
  public Object visit(ASTBNode node, Object data) throws VisitorException;
  public Object visit(ASTLiteral node, Object data) throws VisitorException;
  public Object visit(ASTString node, Object data) throws VisitorException;
  public Object visit(ASTNull node, Object data) throws VisitorException;
}
/* JavaCC - OriginalChecksum=10d665e0123e9d9d5fe36399a555e821 (do not edit this line) */
