/* Generated By:JavaCC: Do not edit this line. SyntaxTreeBuilderTreeConstants.java Version 5.0 */
package org.openrdf.query.parser.serql.ast;

public interface SyntaxTreeBuilderTreeConstants
{
  public int JJTQUERYCONTAINER = 0;
  public int JJTVOID = 1;
  public int JJTNAMESPACEDECL = 2;
  public int JJTTUPLEUNION = 3;
  public int JJTTUPLEMINUS = 4;
  public int JJTTUPLEINTERSECT = 5;
  public int JJTGRAPHUNION = 6;
  public int JJTGRAPHMINUS = 7;
  public int JJTGRAPHINTERSECT = 8;
  public int JJTSELECTQUERY = 9;
  public int JJTSELECT = 10;
  public int JJTPROJECTIONELEM = 11;
  public int JJTCONSTRUCTQUERY = 12;
  public int JJTCONSTRUCT = 13;
  public int JJTQUERYBODY = 14;
  public int JJTFROM = 15;
  public int JJTWHERE = 16;
  public int JJTLIMIT = 17;
  public int JJTOFFSET = 18;
  public int JJTBASICPATHEXPR = 19;
  public int JJTOPTPATHEXPR = 20;
  public int JJTBASICPATHEXPRTAIL = 21;
  public int JJTOPTPATHEXPRTAIL = 22;
  public int JJTEDGE = 23;
  public int JJTNODE = 24;
  public int JJTNODEELEM = 25;
  public int JJTREIFIEDSTAT = 26;
  public int JJTOR = 27;
  public int JJTAND = 28;
  public int JJTBOOLEANCONSTANT = 29;
  public int JJTNOT = 30;
  public int JJTBOUND = 31;
  public int JJTSAMETERM = 32;
  public int JJTISRESOURCE = 33;
  public int JJTISLITERAL = 34;
  public int JJTISURI = 35;
  public int JJTISBNODE = 36;
  public int JJTLANGMATCHES = 37;
  public int JJTREGEX = 38;
  public int JJTEXISTS = 39;
  public int JJTCOMPARE = 40;
  public int JJTCOMPAREANY = 41;
  public int JJTCOMPAREALL = 42;
  public int JJTLIKE = 43;
  public int JJTIN = 44;
  public int JJTINLIST = 45;
  public int JJTCOMPOPERATOR = 46;
  public int JJTVAR = 47;
  public int JJTDATATYPE = 48;
  public int JJTLANG = 49;
  public int JJTLABEL = 50;
  public int JJTNAMESPACE = 51;
  public int JJTLOCALNAME = 52;
  public int JJTSTR = 53;
  public int JJTFUNCTIONCALL = 54;
  public int JJTARGLIST = 55;
  public int JJTURI = 56;
  public int JJTQNAME = 57;
  public int JJTBNODE = 58;
  public int JJTLITERAL = 59;
  public int JJTSTRING = 60;
  public int JJTNULL = 61;


  public String[] jjtNodeName = {
    "QueryContainer",
    "void",
    "NamespaceDecl",
    "TupleUnion",
    "TupleMinus",
    "TupleIntersect",
    "GraphUnion",
    "GraphMinus",
    "GraphIntersect",
    "SelectQuery",
    "Select",
    "ProjectionElem",
    "ConstructQuery",
    "Construct",
    "QueryBody",
    "From",
    "Where",
    "Limit",
    "Offset",
    "BasicPathExpr",
    "OptPathExpr",
    "BasicPathExprTail",
    "OptPathExprTail",
    "Edge",
    "Node",
    "NodeElem",
    "ReifiedStat",
    "Or",
    "And",
    "BooleanConstant",
    "Not",
    "Bound",
    "SameTerm",
    "IsResource",
    "IsLiteral",
    "IsURI",
    "IsBNode",
    "LangMatches",
    "Regex",
    "Exists",
    "Compare",
    "CompareAny",
    "CompareAll",
    "Like",
    "In",
    "InList",
    "CompOperator",
    "Var",
    "Datatype",
    "Lang",
    "Label",
    "Namespace",
    "LocalName",
    "Str",
    "FunctionCall",
    "ArgList",
    "URI",
    "QName",
    "BNode",
    "Literal",
    "String",
    "Null",
  };
}
/* JavaCC - OriginalChecksum=9e5b5315b33e099ea2a7dc9b387de66b (do not edit this line) */
