/* Generated By:JJTree&JavaCC: Do not edit this line. SyntaxTreeBuilderConstants.java */
package org.openrdf.querylanguage.serql.ast;

public interface SyntaxTreeBuilderConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int EQ = 6;
  int NE = 7;
  int LT = 8;
  int LE = 9;
  int GE = 10;
  int GT = 11;
  int STAR = 12;
  int COMMA = 13;
  int SEMICOLON = 14;
  int LBRACE = 15;
  int RBRACE = 16;
  int LPAREN = 17;
  int RPAREN = 18;
  int LBRACK = 19;
  int RBRACK = 20;
  int USING = 21;
  int NAMESPACE = 22;
  int SELECT = 23;
  int CONSTRUCT = 24;
  int DISTINCT = 25;
  int FROM = 26;
  int CONTEXT = 27;
  int WHERE = 28;
  int LIMIT = 29;
  int OFFSET = 30;
  int TRUE = 31;
  int FALSE = 32;
  int NOT = 33;
  int AND = 34;
  int OR = 35;
  int LIKE = 36;
  int IGNORE = 37;
  int CASE = 38;
  int LABEL = 39;
  int LANG = 40;
  int DATATYPE = 41;
  int LOCALNAME = 42;
  int NULL = 43;
  int ISRESOURCE = 44;
  int ISBNODE = 45;
  int ISURI = 46;
  int ISLITERAL = 47;
  int AS = 48;
  int UNION = 49;
  int MINUS = 50;
  int INTERSECT = 51;
  int ANY = 52;
  int ALL = 53;
  int IN = 54;
  int EXISTS = 55;
  int LANG_LITERAL = 56;
  int DATATYPED_LITERAL = 57;
  int STRING = 58;
  int SAFE_CHAR = 59;
  int ESCAPED_CHAR = 60;
  int UNICODE_ESC = 61;
  int LANG_TAG = 62;
  int URI = 63;
  int SCHEME = 64;
  int QNAME = 65;
  int BNODE = 66;
  int PREFIX_NAME = 67;
  int POS_INTEGER = 68;
  int NEG_INTEGER = 69;
  int DECIMAL = 70;
  int HEX = 71;
  int ALPHA = 72;
  int NUM = 73;
  int NCNAME = 74;
  int NCNAME_CHAR = 75;
  int LETTER = 76;
  int BASECHAR = 77;
  int IDEOGRAPHIC = 78;
  int COMBINING_CHAR = 79;
  int DIGIT = 80;
  int EXTENDER = 81;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\">\"",
    "\"*\"",
    "\",\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"using\"",
    "\"namespace\"",
    "\"select\"",
    "\"construct\"",
    "\"distinct\"",
    "\"from\"",
    "\"context\"",
    "\"where\"",
    "\"limit\"",
    "\"offset\"",
    "\"true\"",
    "\"false\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"like\"",
    "\"ignore\"",
    "\"case\"",
    "\"label\"",
    "\"lang\"",
    "\"datatype\"",
    "\"localname\"",
    "\"null\"",
    "\"isResource\"",
    "\"isBNode\"",
    "\"isURI\"",
    "\"isLiteral\"",
    "\"as\"",
    "\"union\"",
    "\"minus\"",
    "\"intersect\"",
    "\"any\"",
    "\"all\"",
    "\"in\"",
    "\"exists\"",
    "<LANG_LITERAL>",
    "<DATATYPED_LITERAL>",
    "<STRING>",
    "<SAFE_CHAR>",
    "<ESCAPED_CHAR>",
    "<UNICODE_ESC>",
    "<LANG_TAG>",
    "<URI>",
    "<SCHEME>",
    "<QNAME>",
    "<BNODE>",
    "<PREFIX_NAME>",
    "<POS_INTEGER>",
    "<NEG_INTEGER>",
    "<DECIMAL>",
    "<HEX>",
    "<ALPHA>",
    "<NUM>",
    "<NCNAME>",
    "<NCNAME_CHAR>",
    "<LETTER>",
    "<BASECHAR>",
    "<IDEOGRAPHIC>",
    "<COMBINING_CHAR>",
    "<DIGIT>",
    "<EXTENDER>",
  };

}
