/* Generated By:JJTree: Do not edit this line. ASTBlankNode.java */

package org.openrdf.querylanguage.sparql.ast;

public class ASTBlankNode extends SimpleNode {

	private String _id;

	public ASTBlankNode(int id) {
		super(id);
	}

	public ASTBlankNode(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public String getID() {
		return _id;
	}

	public void setID(String id) {
		_id = id;
	}

	public String toString() {
		return super.toString() + " (" + _id + ")";
	}
}
