/* Generated By:JJTree: Do not edit this line. ASTConstruct.java */

package org.openrdf.querylanguage.sparql.ast;

public class ASTConstruct extends SimpleNode {

	public ASTConstruct(int id) {
		super(id);
	}

	public ASTConstruct(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}
}
