/* Generated By:JJTree: Do not edit this line. ASTCompare.java */

package org.openrdf.querylanguage.sparql.ast;

import org.openrdf.querymodel.Compare;

public class ASTCompare extends SimpleNode {

	private Compare.Operator _operator;

	public ASTCompare(int id) {
		super(id);
	}

	public ASTCompare(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public Compare.Operator getOperator() {
		return _operator;
	}

	public void setOperator(Compare.Operator operator) {
		_operator = operator;
	}

	public String toString() {
		return super.toString() + " (" + _operator + ")";
	}
}
