/* Generated By:JJTree: Do not edit this line. ASTIsLiteral.java */

package org.openrdf.querylanguage.sparql.ast;

public class ASTIsLiteral extends SimpleNode {

	public ASTIsLiteral(int id) {
		super(id);
	}

	public ASTIsLiteral(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}
}
