/* Generated By:JJTree: Do not edit this line. ASTMath.java */

package org.openrdf.querylanguage.sparql.ast;

import org.openrdf.querymodel.MathExpr;

public class ASTMath extends SimpleNode {

	private MathExpr.Operator _operator;

	public ASTMath(int id) {
		super(id);
	}

	public ASTMath(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public MathExpr.Operator getOperator() {
		return _operator;
	}

	public void setOperator(MathExpr.Operator operator) {
		_operator = operator;
	}
	
	public String toString() {
		return super.toString() + " (" + _operator + ")";
	}
}
