/* Generated By:JJTree: Do not edit this line. ASTOrderClause.java */

package org.openrdf.querylanguage.sparql.ast;

public class ASTOrderClause extends SimpleNode {

	public ASTOrderClause(int id) {
		super(id);
	}

	public ASTOrderClause(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}
}
