/* Generated By:JJTree: Do not edit this line. ASTPrefixDecl.java */

package org.openrdf.querylanguage.sparql.ast;

public class ASTPrefixDecl extends SimpleNode {

	private String _prefix;

	public ASTPrefixDecl(int id) {
		super(id);
	}

	public ASTPrefixDecl(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public String getPrefix() {
		return _prefix;
	}

	public void setPrefix(String prefix) {
		_prefix = prefix;
	}

	public ASTIRI getIRI() {
		return jjtGetChild(ASTIRI.class);
	}

	public String toString() {
		return super.toString() + " (prefix=" + _prefix + ")";
	}
}
