/* Generated By:JJTree: Do not edit this line. ASTVar.java */

package org.openrdf.querylanguage.sparql.ast;

public class ASTVar extends SimpleNode {

	private String _name;

	private boolean _anonymous;

	public ASTVar(int id) {
		super(id);
	}

	public ASTVar(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public String getName() {
		return _name;
	}

	public void setName(String name) {
		_name = name;
	}

	public String toString() {
		return super.toString() + " (" + _name + ")";
	}

	public boolean isAnonymous() {
		return _anonymous;
	}

	public void setAnonymous(boolean anonymous) {
		_anonymous = anonymous;
	}
}
