/*******************************************************************************
 * Copyright (c) 2015, Eclipse Foundation, Inc. and its licensors.
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * - Neither the name of the Eclipse Foundation, Inc. nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission. 
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *******************************************************************************/
package org.eclipse.rdf4j.rio;

/**
 * An interface defining methods for receiving warning and error messages from
 * an RDF parser.
 */
public interface ParseErrorListener {

	/**
	 * Reports a warning from the parser. Warning messages are generated by the
	 * parser when it encounters data that is syntactically correct but which is
	 * likely to be a typo. Examples are the use of unknown or deprecated RDF
	 * URIs, e.g. <tt>rdfs:Property</tt> instead of <tt>rdf:Property</tt>.
	 *
	 * @param msg
	 *        A warning message.
	 * @param lineNo
	 *        A line number related to the warning, or -1 if not available or
	 *        applicable.
	 * @param colNo
	 *        A column number related to the warning, or -1 if not available or
	 *        applicable.
	 * @since 4.0
	 */
	public void warning(String msg, long lineNo, long colNo);

	/**
	 * Reports an error from the parser. Error messages are generated by the
	 * parser when it encounters an error in the RDF document. The parser will
	 * try its best to recover from the error and continue parsing when
	 * <tt>stopAtFirstError</tt> has been set to <tt>false</tt>.
	 *
	 * @param msg
	 *        A error message.
	 * @param lineNo
	 *        A line number related to the error, or -1 if not available or
	 *        applicable.
	 * @param colNo
	 *        A column number related to the error, or -1 if not available or
	 *        applicable.
	 * @see org.eclipse.rdf4j.rio.RDFParser#setStopAtFirstError
	 * @since 4.0
	 */
	public void error(String msg, long lineNo, long colNo);

	/**
	 * Reports a fatal error from the parser. A fatal error is an error of which
	 * the RDF parser cannot recover. The parser will stop parsing directly
	 * after it reported the fatal error. Example fatal errors are unbalanced
	 * start- and end-tags in an XML-encoded RDF document.
	 *
	 * @param msg
	 *        A error message.
	 * @param lineNo
	 *        A line number related to the error, or -1 if not available or
	 *        applicable.
	 * @param colNo
	 *        A column number related to the error, or -1 if not available or
	 *        applicable.
	 * @since 4.0
	 */
	public void fatalError(String msg, long lineNo, long colNo);
}
