/* Generated By:JJTree: Do not edit this line. ASTAskQuery.java */

package org.openrdf.querylanguage.sparql.ast;

public class ASTAskQuery extends ASTQuery {

	public ASTAskQuery(int id) {
		super(id);
	}

	public ASTAskQuery(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}
}
