/* Generated By:JJTree: Do not edit this line. ASTLimitClause.java */

package org.openrdf.querylanguage.sparql.ast;

public class ASTLimit extends SimpleNode {

	private int _value;

	public ASTLimit(int id) {
		super(id);
	}

	public ASTLimit(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public int getValue() {
		return _value;
	}

	public void setValue(int value) {
		_value = value;
	}
	
	public String toString() {
		return super.toString() + " (" + _value + ")";
	}
}
