/* Generated By:JJTree: Do not edit this line. ASTObjectList.java */

package org.openrdf.querylanguage.sparql.ast;

public class ASTObjectList extends SimpleNode {

	public ASTObjectList(int id) {
		super(id);
	}

	public ASTObjectList(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}
}
