/* Generated By:JJTree: Do not edit this line. ASTSelectQuery.java */

package org.openrdf.querylanguage.sparql.ast;

public class ASTSelectQuery extends ASTQuery {

	public ASTSelectQuery(int id) {
		super(id);
	}

	public ASTSelectQuery(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public ASTSelect getSelect() {
		return jjtGetChild(ASTSelect.class);
	}
}
