/* Generated By:JJTree&JavaCC: Do not edit this line. SyntaxTreeBuilderConstants.java */
package org.openrdf.querylanguage.sparql.ast;

public interface SyntaxTreeBuilderConstants {

  int EOF = 0;
  int WS_CHAR = 1;
  int WHITESPACE = 2;
  int SINGLE_LINE_COMMENT = 3;
  int LPAREN = 4;
  int RPAREN = 5;
  int LBRACE = 6;
  int RBRACE = 7;
  int LBRACK = 8;
  int RBRACK = 9;
  int SEMICOLON = 10;
  int COMMA = 11;
  int DOT = 12;
  int EQ = 13;
  int NE = 14;
  int GT = 15;
  int LT = 16;
  int LE = 17;
  int GE = 18;
  int NOT = 19;
  int OR = 20;
  int AND = 21;
  int PLUS = 22;
  int MINUS = 23;
  int STAR = 24;
  int SLASH = 25;
  int DT_PREFIX = 26;
  int NIL = 27;
  int ANON = 28;
  int IS_A = 29;
  int BASE = 30;
  int PREFIX = 31;
  int SELECT = 32;
  int CONSTRUCT = 33;
  int DESCRIBE = 34;
  int ASK = 35;
  int DISTINCT = 36;
  int FROM = 37;
  int NAMED = 38;
  int WHERE = 39;
  int ORDER = 40;
  int BY = 41;
  int ASC = 42;
  int DESC = 43;
  int LIMIT = 44;
  int OFFSET = 45;
  int OPTIONAL = 46;
  int GRAPH = 47;
  int UNION = 48;
  int FILTER = 49;
  int STR = 50;
  int LANG = 51;
  int LANGMATCHES = 52;
  int DATATYPE = 53;
  int BOUND = 54;
  int IS_IRI = 55;
  int IS_BLANK = 56;
  int IS_LITERAL = 57;
  int REGEX = 58;
  int TRUE = 59;
  int FALSE = 60;
  int Q_IRI_REF = 61;
  int QNAME_NS = 62;
  int QNAME = 63;
  int BLANK_NODE_LABEL = 64;
  int VAR1 = 65;
  int VAR2 = 66;
  int LANGTAG = 67;
  int INTEGER = 68;
  int DECIMAL = 69;
  int DECIMAL1 = 70;
  int DECIMAL2 = 71;
  int DOUBLE = 72;
  int DOUBLE1 = 73;
  int DOUBLE2 = 74;
  int DOUBLE3 = 75;
  int EXPONENT = 76;
  int STRING_LITERAL1 = 77;
  int STRING_LITERAL2 = 78;
  int STRING_LITERAL_LONG1 = 79;
  int STRING_LITERAL_LONG2 = 80;
  int SAFE_CHAR1 = 81;
  int SAFE_CHAR2 = 82;
  int SAFE_CHAR_LONG1 = 83;
  int SAFE_CHAR_LONG2 = 84;
  int ECHAR = 85;
  int HEX = 86;
  int ALPHA = 87;
  int NUM = 88;
  int PREFIX_START_CHAR = 89;
  int NCNAME_START_CHAR = 90;
  int VAR_START_CHAR = 91;
  int VAR_CHAR = 92;
  int NCNAME_END_CHAR = 93;
  int NCCHAR = 94;
  int NCNAME_PREFIX = 95;
  int NCNAME = 96;
  int VARNAME = 97;
  int UNKNOWN = 98;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<WS_CHAR>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "<NIL>",
    "<ANON>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"construct\"",
    "\"describe\"",
    "\"ask\"",
    "\"distinct\"",
    "\"from\"",
    "\"named\"",
    "\"where\"",
    "\"order\"",
    "\"by\"",
    "\"asc\"",
    "\"desc\"",
    "\"limit\"",
    "\"offset\"",
    "\"optional\"",
    "\"graph\"",
    "\"union\"",
    "\"filter\"",
    "\"str\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"datatype\"",
    "\"bound\"",
    "<IS_IRI>",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"regex\"",
    "\"true\"",
    "\"false\"",
    "<Q_IRI_REF>",
    "<QNAME_NS>",
    "<QNAME>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANGTAG>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DECIMAL1>",
    "<DECIMAL2>",
    "<DOUBLE>",
    "<DOUBLE1>",
    "<DOUBLE2>",
    "<DOUBLE3>",
    "<EXPONENT>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "<SAFE_CHAR1>",
    "<SAFE_CHAR2>",
    "<SAFE_CHAR_LONG1>",
    "<SAFE_CHAR_LONG2>",
    "<ECHAR>",
    "<HEX>",
    "<ALPHA>",
    "<NUM>",
    "<PREFIX_START_CHAR>",
    "<NCNAME_START_CHAR>",
    "<VAR_START_CHAR>",
    "<VAR_CHAR>",
    "<NCNAME_END_CHAR>",
    "<NCCHAR>",
    "<NCNAME_PREFIX>",
    "<NCNAME>",
    "<VARNAME>",
    "<UNKNOWN>",
  };

}
