/* Generated By:JavaCC: Do not edit this line. SyntaxTreeBuilderTreeConstants.java Version 4.2 */
package org.openrdf.query.parser.sparql.ast;

public interface SyntaxTreeBuilderTreeConstants
{
  public int JJTQUERYCONTAINER = 0;
  public int JJTVOID = 1;
  public int JJTBASEDECL = 2;
  public int JJTPREFIXDECL = 3;
  public int JJTSELECTQUERY = 4;
  public int JJTSELECT = 5;
  public int JJTPROJECTIONELEM = 6;
  public int JJTCONSTRUCTQUERY = 7;
  public int JJTCONSTRUCT = 8;
  public int JJTDESCRIBEQUERY = 9;
  public int JJTDESCRIBE = 10;
  public int JJTASKQUERY = 11;
  public int JJTDATASETCLAUSE = 12;
  public int JJTWHERECLAUSE = 13;
  public int JJTORDERCLAUSE = 14;
  public int JJTORDERCONDITION = 15;
  public int JJTLIMIT = 16;
  public int JJTOFFSET = 17;
  public int JJTGRAPHPATTERNGROUP = 18;
  public int JJTBASICGRAPHPATTERN = 19;
  public int JJTOPTIONALGRAPHPATTERN = 20;
  public int JJTGRAPHGRAPHPATTERN = 21;
  public int JJTUNIONGRAPHPATTERN = 22;
  public int JJTCONSTRAINT = 23;
  public int JJTFUNCTIONCALL = 24;
  public int JJTTRIPLESSAMESUBJECT = 25;
  public int JJTPROPERTYLIST = 26;
  public int JJTOBJECTLIST = 27;
  public int JJTIRI = 28;
  public int JJTBLANKNODEPROPERTYLIST = 29;
  public int JJTCOLLECTION = 30;
  public int JJTVAR = 31;
  public int JJTOR = 32;
  public int JJTAND = 33;
  public int JJTCOMPARE = 34;
  public int JJTMATH = 35;
  public int JJTNOT = 36;
  public int JJTNUMERICLITERAL = 37;
  public int JJTSTR = 38;
  public int JJTLANG = 39;
  public int JJTLANGMATCHES = 40;
  public int JJTDATATYPE = 41;
  public int JJTBOUND = 42;
  public int JJTSAMETERM = 43;
  public int JJTISIRI = 44;
  public int JJTISBLANK = 45;
  public int JJTISLITERAL = 46;
  public int JJTREGEXEXPRESSION = 47;
  public int JJTRDFLITERAL = 48;
  public int JJTTRUE = 49;
  public int JJTFALSE = 50;
  public int JJTSTRING = 51;
  public int JJTQNAME = 52;
  public int JJTBLANKNODE = 53;


  public String[] jjtNodeName = {
    "QueryContainer",
    "void",
    "BaseDecl",
    "PrefixDecl",
    "SelectQuery",
    "Select",
    "ProjectionElem",
    "ConstructQuery",
    "Construct",
    "DescribeQuery",
    "Describe",
    "AskQuery",
    "DatasetClause",
    "WhereClause",
    "OrderClause",
    "OrderCondition",
    "Limit",
    "Offset",
    "GraphPatternGroup",
    "BasicGraphPattern",
    "OptionalGraphPattern",
    "GraphGraphPattern",
    "UnionGraphPattern",
    "Constraint",
    "FunctionCall",
    "TriplesSameSubject",
    "PropertyList",
    "ObjectList",
    "IRI",
    "BlankNodePropertyList",
    "Collection",
    "Var",
    "Or",
    "And",
    "Compare",
    "Math",
    "Not",
    "NumericLiteral",
    "Str",
    "Lang",
    "LangMatches",
    "Datatype",
    "Bound",
    "SameTerm",
    "IsIRI",
    "IsBlank",
    "IsLiteral",
    "RegexExpression",
    "RDFLiteral",
    "True",
    "False",
    "String",
    "QName",
    "BlankNode",
  };
}
/* JavaCC - OriginalChecksum=6f7ec36537db42d050fa93f12c173e86 (do not edit this line) */
