/* Generated By:JJTree&JavaCC: Do not edit this line. SyntaxTreeBuilderConstants.java */
package org.openrdf.query.parser.sparql.ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxTreeBuilderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WS_CHAR = 1;
  /** RegularExpression Id. */
  int WHITESPACE = 2;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int LPAREN = 4;
  /** RegularExpression Id. */
  int RPAREN = 5;
  /** RegularExpression Id. */
  int LBRACE = 6;
  /** RegularExpression Id. */
  int RBRACE = 7;
  /** RegularExpression Id. */
  int LBRACK = 8;
  /** RegularExpression Id. */
  int RBRACK = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int DOT = 12;
  /** RegularExpression Id. */
  int EQ = 13;
  /** RegularExpression Id. */
  int NE = 14;
  /** RegularExpression Id. */
  int GT = 15;
  /** RegularExpression Id. */
  int LT = 16;
  /** RegularExpression Id. */
  int LE = 17;
  /** RegularExpression Id. */
  int GE = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int STAR = 24;
  /** RegularExpression Id. */
  int SLASH = 25;
  /** RegularExpression Id. */
  int DT_PREFIX = 26;
  /** RegularExpression Id. */
  int NIL = 27;
  /** RegularExpression Id. */
  int ANON = 28;
  /** RegularExpression Id. */
  int IS_A = 29;
  /** RegularExpression Id. */
  int BASE = 30;
  /** RegularExpression Id. */
  int PREFIX = 31;
  /** RegularExpression Id. */
  int SELECT = 32;
  /** RegularExpression Id. */
  int CONSTRUCT = 33;
  /** RegularExpression Id. */
  int DESCRIBE = 34;
  /** RegularExpression Id. */
  int ASK = 35;
  /** RegularExpression Id. */
  int DISTINCT = 36;
  /** RegularExpression Id. */
  int REDUCED = 37;
  /** RegularExpression Id. */
  int AS = 38;
  /** RegularExpression Id. */
  int FROM = 39;
  /** RegularExpression Id. */
  int NAMED = 40;
  /** RegularExpression Id. */
  int WHERE = 41;
  /** RegularExpression Id. */
  int ORDER = 42;
  /** RegularExpression Id. */
  int BY = 43;
  /** RegularExpression Id. */
  int ASC = 44;
  /** RegularExpression Id. */
  int DESC = 45;
  /** RegularExpression Id. */
  int LIMIT = 46;
  /** RegularExpression Id. */
  int OFFSET = 47;
  /** RegularExpression Id. */
  int OPTIONAL = 48;
  /** RegularExpression Id. */
  int GRAPH = 49;
  /** RegularExpression Id. */
  int UNION = 50;
  /** RegularExpression Id. */
  int FILTER = 51;
  /** RegularExpression Id. */
  int STR = 52;
  /** RegularExpression Id. */
  int LANG = 53;
  /** RegularExpression Id. */
  int LANGMATCHES = 54;
  /** RegularExpression Id. */
  int DATATYPE = 55;
  /** RegularExpression Id. */
  int BOUND = 56;
  /** RegularExpression Id. */
  int SAMETERM = 57;
  /** RegularExpression Id. */
  int IS_IRI = 58;
  /** RegularExpression Id. */
  int IS_BLANK = 59;
  /** RegularExpression Id. */
  int IS_LITERAL = 60;
  /** RegularExpression Id. */
  int REGEX = 61;
  /** RegularExpression Id. */
  int TRUE = 62;
  /** RegularExpression Id. */
  int FALSE = 63;
  /** RegularExpression Id. */
  int Q_IRI_REF = 64;
  /** RegularExpression Id. */
  int PNAME_NS = 65;
  /** RegularExpression Id. */
  int PNAME_LN = 66;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 67;
  /** RegularExpression Id. */
  int VAR1 = 68;
  /** RegularExpression Id. */
  int VAR2 = 69;
  /** RegularExpression Id. */
  int LANGTAG = 70;
  /** RegularExpression Id. */
  int INTEGER = 71;
  /** RegularExpression Id. */
  int INTEGER_POSITIVE = 72;
  /** RegularExpression Id. */
  int INTEGER_NEGATIVE = 73;
  /** RegularExpression Id. */
  int DECIMAL = 74;
  /** RegularExpression Id. */
  int DECIMAL1 = 75;
  /** RegularExpression Id. */
  int DECIMAL2 = 76;
  /** RegularExpression Id. */
  int DECIMAL_POSITIVE = 77;
  /** RegularExpression Id. */
  int DECIMAL_NEGATIVE = 78;
  /** RegularExpression Id. */
  int DOUBLE = 79;
  /** RegularExpression Id. */
  int DOUBLE1 = 80;
  /** RegularExpression Id. */
  int DOUBLE2 = 81;
  /** RegularExpression Id. */
  int DOUBLE3 = 82;
  /** RegularExpression Id. */
  int EXPONENT = 83;
  /** RegularExpression Id. */
  int DOUBLE_POSITIVE = 84;
  /** RegularExpression Id. */
  int DOUBLE_NEGATIVE = 85;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 86;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 87;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 88;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 89;
  /** RegularExpression Id. */
  int SAFE_CHAR1 = 90;
  /** RegularExpression Id. */
  int SAFE_CHAR2 = 91;
  /** RegularExpression Id. */
  int SAFE_CHAR_LONG1 = 92;
  /** RegularExpression Id. */
  int SAFE_CHAR_LONG2 = 93;
  /** RegularExpression Id. */
  int ECHAR = 94;
  /** RegularExpression Id. */
  int HEX = 95;
  /** RegularExpression Id. */
  int ALPHA = 96;
  /** RegularExpression Id. */
  int NUM = 97;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 98;
  /** RegularExpression Id. */
  int PN_CHARS_U = 99;
  /** RegularExpression Id. */
  int PN_START_CHAR = 100;
  /** RegularExpression Id. */
  int VAR_CHAR = 101;
  /** RegularExpression Id. */
  int PN_END_CHAR = 102;
  /** RegularExpression Id. */
  int PN_CHAR = 103;
  /** RegularExpression Id. */
  int PN_PREFIX = 104;
  /** RegularExpression Id. */
  int PN_LOCAL = 105;
  /** RegularExpression Id. */
  int VARNAME = 106;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WS_CHAR>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "<NIL>",
    "<ANON>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"construct\"",
    "\"describe\"",
    "\"ask\"",
    "\"distinct\"",
    "\"reduced\"",
    "\"as\"",
    "\"from\"",
    "\"named\"",
    "\"where\"",
    "\"order\"",
    "\"by\"",
    "\"asc\"",
    "\"desc\"",
    "\"limit\"",
    "\"offset\"",
    "\"optional\"",
    "\"graph\"",
    "\"union\"",
    "\"filter\"",
    "\"str\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"datatype\"",
    "\"bound\"",
    "\"sameTerm\"",
    "<IS_IRI>",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"regex\"",
    "\"true\"",
    "\"false\"",
    "<Q_IRI_REF>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANGTAG>",
    "<INTEGER>",
    "<INTEGER_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL>",
    "<DECIMAL1>",
    "<DECIMAL2>",
    "<DECIMAL_POSITIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE>",
    "<DOUBLE1>",
    "<DOUBLE2>",
    "<DOUBLE3>",
    "<EXPONENT>",
    "<DOUBLE_POSITIVE>",
    "<DOUBLE_NEGATIVE>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "<SAFE_CHAR1>",
    "<SAFE_CHAR2>",
    "<SAFE_CHAR_LONG1>",
    "<SAFE_CHAR_LONG2>",
    "<ECHAR>",
    "<HEX>",
    "<ALPHA>",
    "<NUM>",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_START_CHAR>",
    "<VAR_CHAR>",
    "<PN_END_CHAR>",
    "<PN_CHAR>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
  };

}
