/* Generated By:JavaCC: Do not edit this line. SyntaxTreeBuilderTreeConstants.java Version 5.0 */
package org.openrdf.query.parser.sparql.ast;

public interface SyntaxTreeBuilderTreeConstants
{
  public int JJTQUERYCONTAINER = 0;
  public int JJTVOID = 1;
  public int JJTBASEDECL = 2;
  public int JJTPREFIXDECL = 3;
  public int JJTSELECTQUERY = 4;
  public int JJTSELECT = 5;
  public int JJTPROJECTIONELEM = 6;
  public int JJTCONSTRUCTQUERY = 7;
  public int JJTCONSTRUCT = 8;
  public int JJTDESCRIBEQUERY = 9;
  public int JJTDESCRIBE = 10;
  public int JJTASKQUERY = 11;
  public int JJTDATASETCLAUSE = 12;
  public int JJTWHERECLAUSE = 13;
  public int JJTGROUPCLAUSE = 14;
  public int JJTORDERCLAUSE = 15;
  public int JJTGROUPCONDITION = 16;
  public int JJTHAVINGCLAUSE = 17;
  public int JJTORDERCONDITION = 18;
  public int JJTLIMIT = 19;
  public int JJTOFFSET = 20;
  public int JJTGRAPHPATTERNGROUP = 21;
  public int JJTBASICGRAPHPATTERN = 22;
  public int JJTOPTIONALGRAPHPATTERN = 23;
  public int JJTGRAPHGRAPHPATTERN = 24;
  public int JJTUNIONGRAPHPATTERN = 25;
  public int JJTMINUSGRAPHPATTERN = 26;
  public int JJTCONSTRAINT = 27;
  public int JJTFUNCTIONCALL = 28;
  public int JJTTRIPLESSAMESUBJECT = 29;
  public int JJTPROPERTYLIST = 30;
  public int JJTOBJECTLIST = 31;
  public int JJTTRIPLESSAMESUBJECTPATH = 32;
  public int JJTPROPERTYLISTPATH = 33;
  public int JJTPATHALTERNATIVE = 34;
  public int JJTPATHSEQUENCE = 35;
  public int JJTPATHELT = 36;
  public int JJTIRI = 37;
  public int JJTPATHONEINPROPERTYSET = 38;
  public int JJTPATHMOD = 39;
  public int JJTBLANKNODEPROPERTYLIST = 40;
  public int JJTCOLLECTION = 41;
  public int JJTVAR = 42;
  public int JJTOR = 43;
  public int JJTAND = 44;
  public int JJTCOMPARE = 45;
  public int JJTMATH = 46;
  public int JJTNOT = 47;
  public int JJTNUMERICLITERAL = 48;
  public int JJTCOUNT = 49;
  public int JJTSUM = 50;
  public int JJTMIN = 51;
  public int JJTMAX = 52;
  public int JJTAVG = 53;
  public int JJTSAMPLE = 54;
  public int JJTGROUPCONCAT = 55;
  public int JJTIF = 56;
  public int JJTIN = 57;
  public int JJTNOTIN = 58;
  public int JJTCOALESCE = 59;
  public int JJTSTR = 60;
  public int JJTLANG = 61;
  public int JJTLANGMATCHES = 62;
  public int JJTDATATYPE = 63;
  public int JJTBOUND = 64;
  public int JJTSAMETERM = 65;
  public int JJTISIRI = 66;
  public int JJTISBLANK = 67;
  public int JJTISLITERAL = 68;
  public int JJTISNUMERIC = 69;
  public int JJTBNODEFUNC = 70;
  public int JJTIRIFUNC = 71;
  public int JJTSTRDT = 72;
  public int JJTSTRLANG = 73;
  public int JJTBIND = 74;
  public int JJTREGEXEXPRESSION = 75;
  public int JJTEXISTSFUNC = 76;
  public int JJTNOTEXISTSFUNC = 77;
  public int JJTRDFLITERAL = 78;
  public int JJTTRUE = 79;
  public int JJTFALSE = 80;
  public int JJTSTRING = 81;
  public int JJTQNAME = 82;
  public int JJTBLANKNODE = 83;


  public String[] jjtNodeName = {
    "QueryContainer",
    "void",
    "BaseDecl",
    "PrefixDecl",
    "SelectQuery",
    "Select",
    "ProjectionElem",
    "ConstructQuery",
    "Construct",
    "DescribeQuery",
    "Describe",
    "AskQuery",
    "DatasetClause",
    "WhereClause",
    "GroupClause",
    "OrderClause",
    "GroupCondition",
    "HavingClause",
    "OrderCondition",
    "Limit",
    "Offset",
    "GraphPatternGroup",
    "BasicGraphPattern",
    "OptionalGraphPattern",
    "GraphGraphPattern",
    "UnionGraphPattern",
    "MinusGraphPattern",
    "Constraint",
    "FunctionCall",
    "TriplesSameSubject",
    "PropertyList",
    "ObjectList",
    "TriplesSameSubjectPath",
    "PropertyListPath",
    "PathAlternative",
    "PathSequence",
    "PathElt",
    "IRI",
    "PathOneInPropertySet",
    "PathMod",
    "BlankNodePropertyList",
    "Collection",
    "Var",
    "Or",
    "And",
    "Compare",
    "Math",
    "Not",
    "NumericLiteral",
    "Count",
    "Sum",
    "Min",
    "Max",
    "Avg",
    "Sample",
    "GroupConcat",
    "If",
    "In",
    "NotIn",
    "Coalesce",
    "Str",
    "Lang",
    "LangMatches",
    "Datatype",
    "Bound",
    "SameTerm",
    "IsIRI",
    "IsBlank",
    "IsLiteral",
    "IsNumeric",
    "BNodeFunc",
    "IRIFunc",
    "StrDt",
    "StrLang",
    "Bind",
    "RegexExpression",
    "ExistsFunc",
    "NotExistsFunc",
    "RDFLiteral",
    "True",
    "False",
    "String",
    "QName",
    "BlankNode",
  };
}
/* JavaCC - OriginalChecksum=e6c9f93d063b2b4b561299e7d892c1e4 (do not edit this line) */
