/* Generated By:JJTree: Do not edit this line. .\SyntaxTreeBuilderTreeConstants.java */

package org.openrdf.query.parser.serql.ast;

public interface SyntaxTreeBuilderTreeConstants
{
  public int JJTQUERYCONTAINER = 0;
  public int JJTVOID = 1;
  public int JJTNAMESPACEDECL = 2;
  public int JJTTUPLEUNION = 3;
  public int JJTTUPLEMINUS = 4;
  public int JJTTUPLEINTERSECT = 5;
  public int JJTGRAPHUNION = 6;
  public int JJTGRAPHMINUS = 7;
  public int JJTGRAPHINTERSECT = 8;
  public int JJTSELECTQUERY = 9;
  public int JJTSELECT = 10;
  public int JJTPROJECTIONELEM = 11;
  public int JJTCONSTRUCTQUERY = 12;
  public int JJTCONSTRUCT = 13;
  public int JJTQUERYBODY = 14;
  public int JJTFROM = 15;
  public int JJTWHERE = 16;
  public int JJTLIMIT = 17;
  public int JJTOFFSET = 18;
  public int JJTBASICPATHEXPR = 19;
  public int JJTOPTPATHEXPR = 20;
  public int JJTBASICPATHEXPRTAIL = 21;
  public int JJTOPTPATHEXPRTAIL = 22;
  public int JJTEDGE = 23;
  public int JJTNODE = 24;
  public int JJTNODEELEM = 25;
  public int JJTREIFIEDSTAT = 26;
  public int JJTOR = 27;
  public int JJTAND = 28;
  public int JJTBOOLEANCONSTANT = 29;
  public int JJTNOT = 30;
  public int JJTISRESOURCE = 31;
  public int JJTISLITERAL = 32;
  public int JJTISURI = 33;
  public int JJTISBNODE = 34;
  public int JJTEXISTS = 35;
  public int JJTCOMPARE = 36;
  public int JJTCOMPAREANY = 37;
  public int JJTCOMPAREALL = 38;
  public int JJTLIKE = 39;
  public int JJTIN = 40;
  public int JJTCOMPOPERATOR = 41;
  public int JJTVAR = 42;
  public int JJTDATATYPE = 43;
  public int JJTLANG = 44;
  public int JJTLABEL = 45;
  public int JJTNAMESPACE = 46;
  public int JJTLOCALNAME = 47;
  public int JJTBOUND = 48;
  public int JJTFUNCTIONCALL = 49;
  public int JJTURI = 50;
  public int JJTQNAME = 51;
  public int JJTBNODE = 52;
  public int JJTLITERAL = 53;
  public int JJTSTRING = 54;
  public int JJTNULL = 55;


  public String[] jjtNodeName = {
    "QueryContainer",
    "void",
    "NamespaceDecl",
    "TupleUnion",
    "TupleMinus",
    "TupleIntersect",
    "GraphUnion",
    "GraphMinus",
    "GraphIntersect",
    "SelectQuery",
    "Select",
    "ProjectionElem",
    "ConstructQuery",
    "Construct",
    "QueryBody",
    "From",
    "Where",
    "Limit",
    "Offset",
    "BasicPathExpr",
    "OptPathExpr",
    "BasicPathExprTail",
    "OptPathExprTail",
    "Edge",
    "Node",
    "NodeElem",
    "ReifiedStat",
    "Or",
    "And",
    "BooleanConstant",
    "Not",
    "IsResource",
    "IsLiteral",
    "IsURI",
    "IsBNode",
    "Exists",
    "Compare",
    "CompareAny",
    "CompareAll",
    "Like",
    "In",
    "CompOperator",
    "Var",
    "Datatype",
    "Lang",
    "Label",
    "Namespace",
    "LocalName",
    "Bound",
    "FunctionCall",
    "URI",
    "QName",
    "BNode",
    "Literal",
    "String",
    "Null",
  };
}
