#!/bin/bash

indir=~/Documents/git/sesame/core/http/workbench/src/main/webapp/scripts
srcdir=/tmp/tsout
mkdir -p $srcdir
rm -f $srcdir/*.js*
destdir=~/tomcat7/webapps/openrdf-workbench/scripts
cd $indir
tsc --sourcemap --sourceRoot "/openrdf-workbench/scripts" --outDir $srcdir *.ts
cp $srcdir/*.js* $destdir
echo 'Replaced deployed JavaScript files with compiled TypeScript sersions.'
