/* Generated By:JJTree: Do not edit this line. ASTDatasetClause.java */

package org.openrdf.query.parser.sparql.ast;

public class ASTDatasetClause extends SimpleNode {

	private boolean _named;

	public ASTDatasetClause(int id) {
		super(id);
	}

	public ASTDatasetClause(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public boolean isNamed() {
		return _named;
	}

	public void setNamed(boolean named) {
		_named = named;
	}
	
	public String toString() {
		return super.toString() + " (named=" + _named + ")";
	}
}
