/* Generated By:JJTree: Do not edit this line. ASTSelect.java */

package org.openrdf.query.parser.sparql.ast;

public class ASTSelect extends SimpleNode {

	private boolean _distinct = false;

	private boolean _wildcard = false;

	public ASTSelect(int id) {
		super(id);
	}

	public ASTSelect(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public boolean isDistinct() {
		return _distinct;
	}

	public void setDistinct(boolean distinct) {
		_distinct = distinct;
	}

	public boolean isWildcard() {
		return _wildcard;
	}

	public void setWildcard(boolean wildcard) {
		_wildcard = wildcard;
	}
	
	public String toString() {
		String result = super.toString();
		
		if (_distinct || _wildcard) {
			result += " (";
			if (_distinct) {
				result += " distinct";
			}
			if (_wildcard) {
				result += " *";
			}
			result += " )";
		}
		
		return result;
	}
}
