/* Generated By:JJTree: Do not edit this line. ASTBaseDecl.java */

package org.openrdf.query.parser.sparql.ast;

public class ASTBaseDecl extends SimpleNode {

	private String _iri;

	public ASTBaseDecl(int id) {
		super(id);
	}

	public ASTBaseDecl(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public String getIRI() {
		return _iri;
	}

	public void setIRI(String iri) {
		_iri = iri;
	}

	public String toString() {
		return super.toString() + " (" + _iri + ")";
	}
}
