/* Generated By:JJTree: Do not edit this line. ASTCollection.java */

package org.openrdf.query.parser.sparql.ast;

public class ASTCollection extends SimpleNode {

	private String _varName;

	public ASTCollection(int id) {
		super(id);
	}

	public ASTCollection(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public String getVarName() {
		return _varName;
	}

	public void setVarName(String varName) {
		_varName = varName;
	}
}
