/* Generated By:JJTree: Do not edit this line. ASTConstraint.java */

package org.openrdf.query.parser.sparql.ast;

public class ASTConstraint extends SimpleNode {

	public ASTConstraint(int id) {
		super(id);
	}

	public ASTConstraint(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}
}
