/* Generated By:JJTree: Do not edit this line. ASTCompare.java */

package org.openrdf.query.parser.sparql.ast;

import org.openrdf.query.algebra.Compare.CompareOp;

public class ASTCompare extends SimpleNode {

	private CompareOp _operator;

	public ASTCompare(int id) {
		super(id);
	}

	public ASTCompare(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public CompareOp getOperator() {
		return _operator;
	}

	public void setOperator(CompareOp operator) {
		_operator = operator;
	}

	public String toString() {
		return super.toString() + " (" + _operator + ")";
	}
}
