/* Generated By:JJTree: Do not edit this line. ASTNumericLiteral.java */

package org.openrdf.query.parser.sparql.ast;

import org.openrdf.model.URI;

public class ASTNumericLiteral extends SimpleNode {

	private String _value;

	private URI _datatype;

	public ASTNumericLiteral(int id) {
		super(id);
	}

	public ASTNumericLiteral(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public String getValue() {
		return _value;
	}

	public void setValue(String value) {
		_value = value;
	}

	public URI getDatatype() {
		return _datatype;
	}

	public void setDatatype(URI datatype) {
		_datatype = datatype;
	}

	public String toString() {
		return super.toString() + " (value=" + _value + ", datatype=" + _datatype + ")";
	}
}
