/* Generated By:JJTree: Do not edit this line. ASTOrderCondition.java */

package org.openrdf.query.parser.sparql.ast;

public class ASTOrderCondition extends SimpleNode {

	private boolean _ascending = true;

	public ASTOrderCondition(int id) {
		super(id);
	}

	public ASTOrderCondition(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public boolean isAscending() {
		return _ascending;
	}

	public void setAscending(boolean ascending) {
		_ascending = ascending;
	}

	public String toString() {
		String result = super.toString();

		if (_ascending) {
			result += " (ASC)";
		}
		else {
			result += " (DESC)";
		}

		return result;
	}
}
